{
 "title": "node_exporter_linux",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "System at a Glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Core Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",fstype=~\"vfat|ext4\"}) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by (sensor)(node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\",instance=\"$node\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "% CPU"
    },
    {
     "expr": "100 * ((node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} )) ",
     "legendFormat": "% RAM"
    },
    {
     "expr": "100 * ((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} )) ",
     "legendFormat": "% Swap"
    },
    {
     "expr": "100 * (sum(node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",fstype!~\"tmpfs\"}) - sum(node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",fstype!~\"tmpfs\"})) / sum(node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",fstype!~\"tmpfs\"})",
     "legendFormat": "% Disk"
    }
   ]
  },
  {
   "title": "Mountpoints",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (sum by (mountpoint)(node_filesystem_free_bytes{instance=\"$node\",job=\"$job\",fstype!~\"tmpfs\"}) / sum by (mountpoint)(node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",fstype!~\"tmpfs\"})))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU (ALL)",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 *(sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\",job=\"$job\"}[5m])))",
       "legendFormat": "%system"
      },
      {
       "expr": "100 * (sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=\"$node\",job=\"$job\"}[5m])))",
       "legendFormat": "%user"
      },
      {
       "expr": "100 * (sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=\"$node\",job=\"$job\"}[5m])))",
       "legendFormat": "%Iowait"
      },
      {
       "expr": "100 * (sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=\"$node\",job=\"$job\"}[5m])))",
       "legendFormat": "%nice"
      },
      {
       "expr": "100 * (sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=\"$node\",job=\"$job\"}[5m])))",
       "legendFormat": "%irq"
      },
      {
       "expr": "100 * (sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=\"$node\",job=\"$job\"}[5m])))",
       "legendFormat": "%softirq"
      },
      {
       "expr": "100 * (sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=\"$node\",job=\"$job\"}[5m])))",
       "legendFormat": "%steal"
      },
      {
       "expr": "100 * (sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=\"$node\",job=\"$job\"}[5m])))",
       "legendFormat": "%guest"
      }
     ]
    },
    {
     "title": "CPU (N) - system/user",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * (sum by (cpu)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\",job=\"$job\"}[5m])))",
       "legendFormat": "%system - cpu{{cpu}}"
      },
      {
       "expr": "100 * (sum by (cpu)(irate(node_cpu_seconds_total{mode='user',instance=\"$node\",job=\"$job\"}[5m])))",
       "legendFormat": "%user - cpu{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU (N) - iowait/nice",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * (sum by (cpu)(irate(node_cpu_seconds_total{mode=\"iowait\",instance=\"$node\",job=\"$job\"}[5m])))",
       "legendFormat": "%iowait - cpu{{cpu}}"
      },
      {
       "expr": "100 * (sum by (cpu)(irate(node_cpu_seconds_total{mode=\"nice\",instance=\"$node\",job=\"$job\"}[5m])))",
       "legendFormat": "%nice - cpu{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU (N) - irq/softirq",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * (sum by (cpu)(irate(node_cpu_seconds_total{mode=\"irq\",instance=\"$node\",job=\"$job\"}[5m])))",
       "legendFormat": "%irq - cpu{{cpu}}"
      },
      {
       "expr": "100 * (sum by (cpu)(irate(node_cpu_seconds_total{mode=\"softirq\",instance=\"$node\",job=\"$job\"}[5m])))",
       "legendFormat": "%softirq - cpu{{cpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device read/write (bytes)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\"}[1m])",
       "legendFormat": "read - {{device}}"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\"}[1m])",
       "legendFormat": "write - {{device}}"
      }
     ]
    },
    {
     "title": "Device read/write (seconds)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total{instance=\"$node\",job=\"$job\"}[1m])",
       "legendFormat": "read - {{device}}"
      },
      {
       "expr": "rate(node_disk_write_time_seconds_total{instance=\"$node\",job=\"$job\"}[1m])",
       "legendFormat": "write - {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "  ",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "free"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} ",
       "legendFormat": "buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "cache"
      },
      {
       "expr": "node_memory_Shmem_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "shared"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "available"
      }
     ]
    },
    {
     "title": "Commit / Used",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * (node_memory_Committed_AS_bytes{instance=\"$node\",job=\"$job\"} / node_memory_CommitLimit_bytes{instance=\"$node\",job=\"$job\"})",
       "legendFormat": "%commit"
      },
      {
       "expr": "100 * (1 - (node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}))",
       "legendFormat": "%mem_used"
      }
     ]
    },
    {
     "title": "Writeback and Dirty",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Writeback"
      },
      {
       "expr": "node_memory_WritebackTmp_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "WritebackTmp"
      },
      {
       "expr": "node_memory_Dirty_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Dirty"
      }
     ]
    },
    {
     "title": "Active / Inactive",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_bytes{instance=\"$node\",job=\"$job\"} ",
       "legendFormat": "Inactive "
      },
      {
       "expr": "node_memory_Active_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Active"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Traffic - Multicast",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_multicast_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - rx"
      }
     ]
    },
    {
     "title": "Drops",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - rx"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - tx"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_errs_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - rx"
      },
      {
       "expr": "irate(node_network_transmit_errs_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "{{device}} - tx"
      }
     ]
    },
    {
     "title": "Softnet Packets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_softnet_processed_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "CPU {{cpu}} - Processed"
      },
      {
       "expr": "irate(node_softnet_dropped_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "CPU {{cpu}} - Dropped"
      }
     ]
    },
    {
     "title": "Softnet - Squeezed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_softnet_times_squeezed_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "CPU {{cpu}}"
      }
     ]
    }
   ]
  },
  { "title": "SockStat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "TCP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "TCP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_mem{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "TCP_mem "
    },
    {
     "expr": "node_sockstat_TCP_orphan{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "TCP_orphan "
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "TCP_tw (time_wait)"
    }
   ]
  },
  {
   "title": "UDP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_UDPLITE_inuse{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "UDPLITE_inuse "
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "UDP_inuse "
    },
    {
     "expr": "node_sockstat_UDP_mem{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "UDP_mem "
    }
   ]
  },
  {
   "title": "Sockets Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "sockets_used "
    }
   ]
  },
  {
   "title": "Socket Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_mem_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "TCP_mem_bytes"
    },
    {
     "expr": "node_sockstat_UDP_mem_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "UDP_mem_bytes"
    }
   ]
  }
 ]
}